package com.mtala3t.steganography.ui;

import com.mtala3t.steganography.util.AudioFileHelper;

public class ShowEmbeddedFile extends WizardPanel {

	java.io.File inputFile, outputFile;

	/** Creates new form ShowOutputFile */
	public ShowEmbeddedFile(String display) {
		super(display);
		initComponents();
		imageSplitPane.setDividerLocation(0.5);
		imageSplitPane.revalidate();

		choiceButtonGroup.add(inputImageRadioButton);
		choiceButtonGroup.add(outputImageRadioButton);
	}

	public void setImageFiles(java.io.File inputFile, java.io.File outputFile) {
		this.inputFile = inputFile;
		this.outputFile = outputFile;

		inputAudioLabel.setIcon(new javax.swing.ImageIcon(inputFile
				.getAbsolutePath()));
		inputFileNameLabel.setText("Input File : "
				+ inputFile.getAbsolutePath());
		outputAudioLabel.setIcon(new javax.swing.ImageIcon(outputFile
				.getAbsolutePath()));
		outputFileNameLabel.setText("Output File : "
				+ outputFile.getAbsolutePath());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		choiceButtonGroup = new javax.swing.ButtonGroup();
		imageSplitPane = new javax.swing.JSplitPane();
		inputImagePanel = new javax.swing.JPanel();
		inputImageScrollPane = new javax.swing.JScrollPane();
		inputAudioLabel = new javax.swing.JLabel("It's Done.");
		inputFileNameLabel = new javax.swing.JLabel();
		outputImagePanel = new javax.swing.JPanel();
		outputImageScrollPane = new javax.swing.JScrollPane();
		outputAudioLabel = new javax.swing.JLabel();
		outputFileNameLabel = new javax.swing.JLabel();
		optionsPanel = new javax.swing.JPanel();
		inputImageRadioButton = new javax.swing.JRadioButton();
		outputImageRadioButton = new javax.swing.JRadioButton();

		setLayout(new java.awt.BorderLayout());

		imageSplitPane.setDividerLocation(100);
		imageSplitPane.setOneTouchExpandable(true);
		inputImagePanel.setLayout(new java.awt.BorderLayout());

		inputAudioLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		inputImageScrollPane.setViewportView(inputAudioLabel);

		inputImagePanel.add(inputImageScrollPane, java.awt.BorderLayout.CENTER);

		inputImagePanel.add(inputFileNameLabel, java.awt.BorderLayout.NORTH);

		imageSplitPane.setRightComponent(inputImagePanel);

		outputImagePanel.setLayout(new java.awt.BorderLayout());

		outputAudioLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		outputImageScrollPane.setViewportView(outputAudioLabel);

		outputImagePanel.add(outputImageScrollPane,
				java.awt.BorderLayout.CENTER);

		outputImagePanel.add(outputFileNameLabel, java.awt.BorderLayout.CENTER);

		imageSplitPane.setLeftComponent(outputImagePanel);
		
		add(imageSplitPane, java.awt.BorderLayout.CENTER);

		inputImageRadioButton.setMnemonic('O');
		inputImageRadioButton.setText("Play Output Audio");
		inputImageRadioButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						inputImageRadioButtonActionPerformed(evt);
					}
				});

		optionsPanel.add(inputImageRadioButton);

		outputImageRadioButton.setMnemonic('i');
		outputImageRadioButton.setText("Play Input Audio");
		outputImageRadioButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						outputImageRadioButtonActionPerformed(evt);
					}
				});

		
		optionsPanel.add(outputImageRadioButton);
		add(optionsPanel, java.awt.BorderLayout.SOUTH);

	}// GEN-END:initComponents

	private void outputImageRadioButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_outputImageRadioButtonActionPerformed
		// Add your handling code here:
		// imageSplitPane.setDividerLocation(0.0);
		System.out.println("Code to play..");
		System.out.println("Code to Play Audio...");
		System.out.println("AudioFile Path" + outputFile.getParent());
		System.out.println("AudioFile Name..." + outputFile.getName());
		String url = "file:///" + inputFile.getParent() + "//";
		System.out.println("URL.." + url);
		/*
		 * new
		 * SoundApplication("file:///C://Shri//AudioHide//Audio1.4//","music.au"
		 * );
		 */
		AudioFileHelper.playAudio(url, outputFile.getName());
	}// GEN-LAST:event_outputImageRadioButtonActionPerformed

	private void inputImageRadioButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inputImageRadioButtonActionPerformed
		// Add your handling code here:
		// imageSplitPane.setDividerLocation(1.0);
		System.out.println("Code to play..");
		System.out.println("Code to Play Audio...");
		System.out.println("AudioFile Path" + inputFile.getParent());
		System.out.println("AudioFile Name..." + inputFile.getName());
		String url = "file:///" + inputFile.getParent() + "//";
		System.out.println("URL.." + url);
		/*
		 * new
		 * SoundApplication("file:///C://Shri//AudioHide//Audio1.4//","music.au"
		 * );
		 */
		AudioFileHelper.playAudio(url, inputFile.getName());

	}// GEN-LAST:event_inputImageRadioButtonActionPerformed

	public boolean doValidation() {
		return true;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel outputAudioLabel;
	private javax.swing.JScrollPane inputImageScrollPane;
	private javax.swing.JLabel inputFileNameLabel;
	private javax.swing.JRadioButton inputImageRadioButton;
	private javax.swing.JRadioButton outputImageRadioButton;
	private javax.swing.JPanel inputImagePanel;
	private javax.swing.JScrollPane outputImageScrollPane;
	private javax.swing.JLabel outputFileNameLabel;
	private javax.swing.ButtonGroup choiceButtonGroup;
	private javax.swing.JPanel outputImagePanel;
	private javax.swing.JSplitPane imageSplitPane;
	private javax.swing.JPanel optionsPanel;
	private javax.swing.JLabel inputAudioLabel;
	// End of variables declaration//GEN-END:variables

}
